# syntax=docker/dockerfile:1
FROM alpine:3.20.1 AS build
RUN mkdir -p rhc/scripts
COPY rhc/scripts/*.sh rhc/scripts
SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
RUN find rhc/scripts -type f -print0 | xargs -0 dos2unix --

FROM alpine:3.20.1
RUN mkdir -p /app/ocw-minecraft /config /data/defaultconfigs
WORKDIR /app
RUN apk --no-cache add docker=26.1.3-r2 docker-cli-compose=2.27.0-r3 curl=8.8.0-r0 jq=1.7.1-r0
COPY --from=build --chmod=755 rhc/scripts/*.sh .
COPY docker-compose.yaml ocw-minecraft/docker-compose.yaml
COPY *.env ocw-minecraft/
LABEL org.opencontainers.image.source="https://github.com/Nincodedo/rhc-ocw"
ENTRYPOINT ["sh", "/app/resetWorld.sh"]
