FROM debian:buster-slim AS build
RUN apt-get update \
  && apt-get install wget -y --no-install-recommends \
  && apt-get install ca-certificates -y --no-install-recommends \
  && apt-get install dos2unix -y --no-install-recommends \
  && apt-get install unzip -y --no-install-recommends \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
COPY scripts/downloadTekkit2.sh /downloadTekkit2.sh
RUN dos2unix /downloadTekkit2.sh /downloadTekkit2.sh
RUN /downloadTekkit2.sh

FROM itzg/minecraft-server:java8-multiarch

RUN mkdir -p /mods
COPY --from=build /server/mods /mods

RUN mkdir -p /config/config /config/scripts
COPY --from=build /server/config /config/config
COPY --from=build /server/scripts /config/scripts
