FROM debian:buster-slim AS build
RUN apt-get update \
  && apt-get install zip -y --no-install-recommends \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY datapacks /datapacks
RUN cd /datapacks/ocw-stuff \
  && zip -r ocw-stuff.zip . \
  && mv ocw-stuff.zip /datapacks \
  && cd /datapacks/who-did-this \
  && zip -r who-did-this.zip . \
  && mv who-did-this.zip /datapacks

FROM itzg/minecraft-server:latest

ENV MODRINTH_PROJECTS=fabric-api,cloth-config,lithium,phosphor,fastback,server-side-replay-recorder,c2me-fabric,netherportalfix,no-chat-reports,rightclickharvest,memoryleakfix,realisticsleep,mc-server-description

ENV DATAPACKS=/datapacks/ocw-stuff.zip,/datapacks/who-did-this.zip
RUN mkdir -p /datapacks
COPY --from=build /datapacks/*.zip /datapacks

ENV VANILLATWEAKS_FILE=/vt/craftingtweaks.json,/vt/datapacks.json
RUN mkdir -p /vt
COPY rhc/vt/*.json /vt

RUN mkdir -p /patches
COPY rhc/patches/*.json /patches
ENV PATCH_DEFINITIONS=/patches

ENV REPLACE_ENV_VARIABLES=true
ENV REPLACE_ENV_DURING_SYNC=true
ENV SYNC_SKIP_NEWER_IN_DESTINATION=false
RUN mkdir /config
COPY rhc/configs/ /config
