# syntax=docker/dockerfile:1
FROM alpine:3.22.2 AS build
RUN mkdir -p rhc/scripts
COPY rhc/scripts/*.sh rhc/scripts
SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
RUN find rhc/scripts -type f -print0 | xargs -0 dos2unix --

FROM alpine:3.22.2
RUN mkdir -p /app/ocw-minecraft /config /data/defaultconfigs
WORKDIR /app
RUN apk --no-cache add docker=28.3.3-r0 docker-cli-compose=2.36.2-r0 curl=8.14.1-r1 jq=1.8.0-r0
COPY --from=build --chmod=755 rhc/scripts/*.sh .
COPY docker-compose.yaml ocw-minecraft/docker-compose.yaml
COPY *.env ocw-minecraft/
LABEL org.opencontainers.image.source="https://github.com/Nincodedo/rhc-ocw"
ENTRYPOINT ["/app/resetWorld.sh"]
