on:
  pull_request:
    branches:
      - main
name: PR on Main Build
jobs:
  buildlw:
    name: Build Log Watcher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-log-watcher
          platforms: linux/amd64
          push: false
          provenance: false
  buildmc:
    name: Build Minecraft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-mc
          platforms: linux/amd64
          push: false
          provenance: false
